"use client";

import { FormEvent, useMemo, useRef, useState } from "react";
import { Icon } from "@/shared/components/ui/icon";
import { PwaInstallButton } from "@/infrastructure/pwa/pwa-register";
import { Modal } from "@/shared/components/ui/modal";
import { useFinance } from "@/shared/providers/finance-provider";
import type { Note } from "@/shared/types/domain";
import { formatDate } from "@/shared/utils/format";

export function PersonalPage(){
  const {state,addNote,updateNote,deleteNote,exportData,importData,resetDemo}=useFinance();
  const [open,setOpen]=useState(false); const [editing,setEditing]=useState<Note|null>(null); const [toast,setToast]=useState(""); const [query,setQuery]=useState(""); const fileRef=useRef<HTMLInputElement>(null);
  const notes=useMemo(()=>state.notes.filter((note)=>`${note.title} ${note.content}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),[state.notes,query]);
  function flash(text:string){setToast(text);window.setTimeout(()=>setToast(""),3000);}
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);const input={title:String(form.get("title")).trim(),content:String(form.get("content")).trim()};if(editing)updateNote(editing.id,input);else addNote(input);setOpen(false);setEditing(null);flash(editing?"Catatan diperbarui.":"Catatan disimpan.");}
  async function importFile(file?:File){if(!file)return;const result=await importData(file);flash(result.message); if(fileRef.current) fileRef.current.value="";}
  function remove(note:Note){if(window.confirm(`Hapus catatan “${note.title}”?`)){deleteNote(note.id);flash("Catatan dihapus.");}}
  function restore(){if(window.confirm("Pulihkan seluruh data demo? Data lokal saat ini akan diganti.")){resetDemo();flash("Data demo dipulihkan.");}}
  return <div className="page-stack"><section className="page-heading"><div><h1>Catatan & data</h1><p>Tempat ringkas untuk catatan pribadi, backup, dan snapshot aktivitas FinanceAI.</p></div><button className="button primary" onClick={()=>{setEditing(null);setOpen(true);}}><Icon name="plus" size={17}/>Catatan</button></section>
  <section className="personal-grid"><article className="card card-secondary span-2"><div className="card-head"><div><h2>Catatan pribadi</h2></div><button className="small-action" onClick={()=>{setEditing(null);setOpen(true);}}><Icon name="plus" size={16}/>Tambah</button></div><div className="notes-toolbar"><div className="inline-search"><Icon name="search" size={16}/><input aria-label="Cari catatan" placeholder="Cari catatan" value={query} onChange={(e)=>setQuery(e.target.value)}/></div><span>{notes.length} catatan</span></div>{notes.length?<div className="notes-grid">{notes.map((note)=><article className="note-card" key={note.id}><div className="note-top"><span className="note-icon"><Icon name="note" size={18}/></span><div className="note-actions"><button type="button" onClick={()=>{setEditing(note);setOpen(true);}}>Edit</button><button type="button" className="danger-link" onClick={()=>remove(note)}>Hapus</button></div></div><h3>{note.title}</h3><p>{note.content}</p><small>Diperbarui {formatDate(note.updatedAt,{day:"2-digit",month:"short",year:"numeric"})}</small></article>)}</div>:<div className="empty-panel"><Icon name="note"/><strong>Tidak ada catatan yang cocok</strong><span>Buat catatan baru atau ubah pencarian.</span></div>}</article>
  <article className="card card-compact backup-card"><h2>Backup lokal</h2><p>Data MVP disimpan di browser. Export JSON bisa dipakai sebagai backup portabel dan import akan divalidasi sebelum diterapkan.</p><div className="backup-actions"><button className="button primary" onClick={exportData}><Icon name="download" size={17}/>Export JSON</button><button className="button ghost" onClick={()=>fileRef.current?.click()}><Icon name="upload" size={17}/>Import</button><input ref={fileRef} type="file" accept="application/json,.json" hidden onChange={(event)=>importFile(event.target.files?.[0])}/></div><PwaInstallButton/><button type="button" className="text-danger" onClick={restore}>Pulihkan data demo</button></article>
  <article className="card card-compact personal-summary"><h2>Ringkasan personal</h2><div className="summary-row"><span>Catatan</span><strong>{state.notes.length}</strong></div><div className="summary-row"><span>Agenda</span><strong>{state.agendas.filter((item)=>!item.done).length}</strong></div><div className="summary-row"><span>Goals aktif</span><strong>{state.goals.filter((item)=>item.status==="active").length}</strong></div><div className="summary-row"><span>Wallet</span><strong>{state.wallets.filter((item)=>!item.archived).length}</strong></div></article></section>
  <Modal open={open} onClose={()=>{setOpen(false);setEditing(null);}} title={editing?"Edit catatan":"Tambah catatan"} description="Catatan tersimpan lokal bersama data FinanceAI lainnya."><form className="form-stack" onSubmit={submit}><label className="field"><span>Judul</span><input name="title" required placeholder="Contoh: Fokus bulan ini" defaultValue={editing?.title??""} autoFocus/></label><label className="field"><span>Isi catatan</span><textarea name="content" rows={6} required placeholder="Tulis apa yang ingin kamu simpan..." defaultValue={editing?.content??""}/></label><div className="modal-actions sticky-actions"><button type="button" className="button ghost" onClick={()=>{setOpen(false);setEditing(null);}}>Batal</button><button className="button primary">Simpan catatan</button></div></form></Modal>{toast&&<div className="toast" role="status">{toast}</div>}</div>;
}
